let initCharacter = {
    "name": "",
    "size": "size-medium",
    "headValue": 0,
    "tmpHeadValue": 0,
    "spiritValue": 0,
    "tmpSpiritValue": 0,
    "heartValue": 0,
    "tmpHeartValue": 0,
    "rightArmValue": 0,
    "tmpRightArmValue": 0,
    "leftArmValue": 0,
    "tmpLeftArmValue": 0,
    "rightLegValue": 0,
    "tmpRightLegValue": 0,
    "leftLegValue": 0,
    "tmpLeftLegValue": 0,
    "enduranceValue": 0,
    "acValue": 0,
    "pacValue": 0,
    "mindValue": 0,
    "strengthValue": 0,
    "agilityValue": 0,
    "willValue": 0,
    "abilityDescription": "",
    "notes": "",
    "skinTone": "#FFEBCD"
}