let initCharacter = {
	"name": "Telekinetic Alter",
	"size": "size-medium",
	"headValue": 2,
	"tmpHeadValue": 1,
	"spiritValue": 2,
	"tmpSpiritValue": 0,
	"heartValue": 1,
	"tmpHeartValue": 0,
	"rightArmValue": 2,
	"tmpRightArmValue": 0,
	"leftArmValue": 1,
	"tmpLeftArmValue": 0,
	"rightLegValue": 2,
	"tmpRightLegValue": 0,
	"leftLegValue": 1,
	"tmpLeftLegValue": 0,
	"enduranceValue": 7,
	"acValue": 4,
	"pacValue": 5,
	"mindValue": 2,
	"strengthValue": 3,
	"agilityValue": 3,
	"willValue": 3,
	"abilityDescription": "Lvl 1\nEnhancements\nCan alter what I cant see\nTelepathy",
	"notes": "Bow\n9 arrows\n\nAllies : Reconstruction man",
	"skinTone": "#FFEBCD"
}